# fly.toml app configuration file generated for alainmarechalchef-back on 2023-10-03T15:30:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alainmarechalchef-back"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
